# Site settings
title: Jossie Haines
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/jossie-web/" # the subpath of your site, e.g. /blog/
url: "https://selfrescuingprincess.github.io" # the base hostname & protocol for your site
author: Copyright &copy; 2020 - Jossie Haines
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
